### ISSUE TITLE
Bad pixel smear with OMLED display

### ISSUE THREAD

**Issue by booty156** [OSVR/OSVR-Docs#115]
How can I solve this? I've correctly added my display to OSVR. But when I moved about the colors smear and it's really bad

**Comment by russell-taylor** [comment]
Strange repository to put this issue on, but glad to try and help.  When I've seen this issue in the past, it has always been a hardware issue on the display.  I verified it by running in Extended Mode (rather than DirectMode) and putting the window on a monitor.  If the smearing goes away on the monitor (as it always has for me), then the issue is that the HMD's switching time (or overshoot or...) is too high.  Nothing software can do to fix that.

**Comment by booty156** [comment]
Sorry about the repository since it has the doc where to add your own HMD I thought I'll put it in. But there was no smearing on the display when I moved a window or when I played an video

**Comment by russell-taylor** [comment]
The SpinCube examples https://github.com/sensics/OSVR-RenderManager/blob/master/examples/SpinCubeOpenGL.cpp were created to help me test this, and worked much better for me than trying to judge from an arbitrary video.  When I run them and display on a monitor, I see no smearing.  When I run them on an Oculus DK2 or on the OSVR HDK 2 I do see smearing.  It is much worse at a linear high-luminance (Red+Green) boundary.
