### ISSUE TITLE
Suggested Edit To Main Page MD

### ISSUE THREAD

**Issue by Balderick** [OSVR/OSVR-Docs#62]
With reference to - https://github.com/OSVR/OSVR-Docs/blob/master/Troubleshooting/RenderManager.md#compatible-gpu-drivers

> To work around this, you'll either need to:
> Disable the other GPU (if possible - e.g., on desktop)
> Stay with a pre-367 driver.

could read

> To work around this, you'll either need to:
> Add another nvidia discrete card which suports hdmi. 
> Disable the other GPU (if possible - e.g., on desktop).
> Stay with a pre-367 driver.
> Use a male display port to female hdmi 2.0 adapter if your only available nvidia gpu has only one hdmi port but available unused display ports to allow both displays be connected to same nvidia gpu.

1194 runtime with 365.19 driver does not work out well with osvr content or steam vr content on a multi gpu set up with just one nvidia hdmi port for hmd.  1194 is the current known stable.   it may be users need to rollback to 1178 or older runtime  with 365.19 and older drivers for the suggested "Stay with a pre-367 driver." workaround to be a workaround.? .

**Comment by rpavlik** [comment]
The OSVR Core version (the 11xx values you mentioned are the last component of the version) does not interact with the graphics driver at all. For OSVR content, all that interacts with the graphics driver is which version of render manager the application was built with. For steam vr, what interacts is steamvr itself, though more automated configuration and direct mode support was added to the plugin recently, it primarily does this by providing information to steamvr.

I've been running a multi GPU setup on NVIDIA with that driver version with 1 hdmi for the HDK,1 dvi for a monitor, then on the Intel adapter, 1 monitor on HDMI. Steamvr does launch, and so does native OSVR content. Unity-based applications are a bit of a pain, requiring an undocumented `-gpu 1` command line argument to keep them from picking the Intel card, but we haven't been able to find a way to work around automatically this in code yet, and from the looks of it neither has steamvr.

I don't quite understand your two suggested workaround additions: does the NVIDIA direct mode disablement not take effect if there are two NVIDIA cards and one non NVIDIA? How does display port factor in? (Just by disabling the Intel card by not using any outputs?)

**Comment by Balderick** [comment]
In my case i have been using a gtx 980 ti for hmd.   That card has only one hdmi port.  The igpu which being used as primary display for windows desktop is intel 530 and has only one hdmi port.

I can not get steamvr apps or osvr content to run in hmd as expected.  The direct mode disablement works fine.  steamvr launches fine.  steam compositor launches in hmd fine.    No app gets rendered in hmd after launching in vr mode.  only windowed version on ptrimary display (4K TV)

steam support specifies the need for main display and hmd connected to same gpu to get by 108/109/400 errors.

How do i connect my hdmi for display and hdmi for hmd to a discrete card with one hdmi port?

Rolling back gpu drivers, adding another nvidia gpu to replace intel igpu for main display, and using a display port to hdmi connector are all work arounds discussed on reddit, github and other sources is at least acknowledgement from others there is an issue with some hardware configurations and osvr software. .   People with one hdmi connector on only discrete gpu and having issues with osvr software seems to be a not too uncommon and long standing issue.

So if your intel and nvidia gpu configuration works for you that would mean i am doing something wrong somewhere.
I guess i need to keep trying different things ...

**Comment by d235j** [comment]
@Balderick What secondary discrete NVIDIA GPU are you using? NVIDIA driver support for older or mismatched cards is less than perfect.
I suggest obtaining an adapter in order to use the DVI port or DisplayPorts with your HDMI monitor. Passive adapters should be quite inexpensive, and should provide full performance at least with HDMI.

**Comment by Balderick** [comment]
Thanks for the feedback @d235j.  I have been trying a gtx 950 with gtx 980 ti non sli setup.   It is looking like both steamvr and vrworks are looking for both primary display and hmd connected to same gpu.   I have tried to describe in more detail what i have been observing over at https://github.com/OSVR/SteamVR-OSVR/issues/75 which is a continuation of https://github.com/OSVR/SteamVR-OSVR/issues/40

Thanks for confirming a male display port to female hdmi 2.0 adaptor (for 4K tv) is more than worth a try to get both displays connected to same gpu.

**Comment by rpavlik** [comment]
If you have a non NVIDIA GPU in your system at all, or are on a laptop, a
post 367 NVIDIA driver won't work in direct mode no matter which card the
HDK is connected to. If you don't like that, tell NVIDIA, it was their
decision to disable the HDK in that way.

If you only have NVIDIA gpus, then there's still a similar problem as what
can happen with earlier driver versions in mixed vendor GPU systems. If the
applications/engines don't let whatever mechanism sets up direct mode
(render manager if you're using native OSVR, the steamvr client+compositor
if you're using steamvr) create the context and device object (unity and
unreal both fall into this category), then they have to basically be lucky
enough to"guess"the right adapter to use, to match the adapter being used
for direct mode. When you've got, say, an Intel adapter and an NVIDIA
adapter, of those two engines only Unity is silly enough to think you want
to render on the Intel adapter, unreal guesses right. (But, there's at
least a workaround via an undocumented command line flag for Unity apps). I
have no idea, however, how the default guesses would match up with whatever
device you choose to use direct mode with when they're both "discrete" and
a similar class. So, curiously, you may get a worse experience with that
setup, simply because popular game engines don't readily delegate the
selection of 3d adapter/creation of associated rendering objects. (If you
try the render manager present example, that should work just fine, because
it takes the easy way and lets render manager do more of the work,
conveniently resulting in the right adapter every time, and also high
priority execution on NVIDIA, etc...)

On Sun, Jul 10, 2016, 11:34 PM Balderick notifications@github.com wrote:

> Thanks for the feedback @d235j https://github.com/d235j. I have been
> trying a gtx 950 with gtx 980 ti non sli setup. It is looking like both
> steamvr and vrworks are looking for both primary display and hmd connected
> to same gpu. I have tried to describe in more detail what i have been
> observing over at OSVR/SteamVR-OSVR#75
> https://github.com/OSVR/SteamVR-OSVR/issues/75 which is a continuation
> of OSVR/SteamVR-OSVR#40 https://github.com/OSVR/SteamVR-OSVR/issues/40
> 
> Thanks for confirming a male display port to female hdmi 2.0 adaptor is
> more than worth a try to get both displays connected to same gpu.
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly, view it on GitHub
> https://github.com/OSVR/OSVR-Docs/issues/62#issuecomment-231640219, or mute
> the thread
> https://github.com/notifications/unsubscribe/AADuyXVhbm2j7uloHSj2Rz5NO3hr_Go9ks5qUce6gaJpZM4JHFxS
> .
> 
> ## 
> 
> Ryan A. Pavlik, Ph.D.
> CTO - OSVR Platform
> Sensics, Inc.
> www.sensics.com

## 

Latest news and blog posts (subscribe here 
http://sensics.com/subscribe-to-our-mailing-list/ to get weekly updates):

July 20: Conversation with Dio Gonzalez, Principal Software Engineer at 
Unity Labs 
http://sensics.com/vrguy-podcast-episode-19-dio-gonzalez-principal-software-developer-unity-labs/

July 19: Sensics and LaputaVR team up to provide OSVR support to LaputaVR 
devices 
http://sensics.com/sensics-laputa-vr-team-provide-osvr-support-laputa-vr-devices/

July 13: VRguy podcast: Shaun Williams, CEO of MAG games 
http://bit.ly/29vCqIW
